FROM ibmcom/ibm-fhir-server:4.2.1
COPY fhir-server-config.json /opt/ol/wlp/usr/servers/fhir-server/config/default/fhir-server-config.json
COPY server.xml /opt/ol/wlp/usr/servers/fhir-server/server.xml